apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
        - name: todoapi
          image: ghcr.io/brandencward/todoapi:latest #ghcr.io/brandencward/todoapi-test:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: web
            protocol: TCP
          readinessProbe:
            httpGet:
              port: web
              path: /swagger
          env:
          - name: CMKR_MY_KEY
            valueFrom:
              configMapKeyRef:
                name: testkeyvalpair
                key: mykey
          - name: CMKR_TESTKEY1
            valueFrom:
              configMapKeyRef:
                name: testkeyvalpair
                key: testkey1
          - name: CMKR_TESTKEY2
            valueFrom:
              configMapKeyRef:
                name: testkeyvalpair
                key: testkey2
          - name: YAML
            value: yamlvalue
          - name: SECRET_ENV_VAR
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: secretkey
          volumeMounts:
          - name: testread
            mountPath: /mnt/tests/test.txt  
            subPath: test.txt          
            readOnly: true
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
      - name: testread
        configMap:
          name: testreadfile
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kv" 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testreadfile
data:
  test.txt: |
    Some MultiLine text.
    Some More text.
    Testing Text.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testkeyvalpair
data:
  mykey: configmapkeyrefvalue
  testkey1: testingkey1
  testkey2: testingkey2
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:  
  secretkey: dGVzdHNlY3JldHMK
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "YOUR IDENTITY"
    keyvaultName: "sandbox-kv-mykeyvault23"
    objects: |
      array:
        - |
          objectName: kv-secret1              
          objectType: secret
          objectVersion: ""
        - |
          objectName: kv-secret2              
          objectType: secret
          objectVersion: ""           
    tenantId: "YOUR TENANT ID"