apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
        - name: todoapi
          image: ghcr.io/brandencward/todoapi-arm:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: web
            protocol: TCP
          readinessProbe:
            httpGet:
              port: web
              path: /swagger
          volumeMounts:
          - name: testread
            mountPath: /mnt/tests/test.txt  
            subPath: test.txt          
            readOnly: true
          - name: nfs
            mountPath: /mnt/ssd  
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
      - name: testread
        configMap:
          name: testreadfile
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testreadfile
data:
  test.txt: |
    Some MultiLine text.
    Some More text.
    Testing Text.
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: "" 
  nfs:
    path: "/mnt/ssd"
    server: "192.168.1.61"
    readOnly: true
  claimRef:
    name: nfs
    namespace: default  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" 
  volumeName: nfs