apiVersion: v1
kind: Service
metadata:
  name: todoapi-nodeport
  namespace: todoapi
spec:
  type: NodePort
  selector:
    app: todoapi
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 31112